name: 🐛 Bug Report
description: Create a bug report to help us fix an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is, and what you expected to happen
      placeholder: Tell us what happened!
      value: ""
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What does this issue relate to?
      options:
      - Gameplay
      - User Interface
      - Game Modes
      - Mod Tools
      - Replays
      - Something Else; Describe below
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Something Else; Describe below
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant site error message, if relevant.
      render: shell
  - type: textarea
    id: extra-details
    attributes:
      label: Extra Context or Details
      description: Add any other context about the problem here (Screenshots Preferred)
      placeholder: <Insert an image!>
      value: ""
