const mongoose = require("mongoose");
const passportLocalMongoose = require("passport-local-mongoose");
const { CURRENT_SEASON_NUMBER, seasonCounterFields } = require("../src/shared/season");
const { STARTING_PUBLIC_RATING } = require("../routes/socket/rating/public-ladder");
const { Schema } = mongoose;

// Keep every historical season while automatically admitting the next season's strict-schema fields.
const seasonalCounters = {};
for (let season = 1; season <= CURRENT_SEASON_NUMBER; season++) {
  for (const field of Object.values(seasonCounterFields(season))) seasonalCounters[field] = Number;
}
const Account = new Schema({
  username: {
    type: String,
    required: true,
    unique: true,
  },
  password: String,
  isLocal: Boolean,
  staffRole: String,
  isContributor: Boolean,
  hasNotDismissedSignupModal: Boolean,
  gameSettings: {
    playerPronouns: String,
    staffDisableVisibleElo: Boolean,
    staffDisableVisibleXP: Boolean,
    staffDisableStaffColor: Boolean,
    staffIncognito: Boolean,
    isRainbow: Boolean,
    newReport: Boolean,
    hasUnseenBadge: Boolean,
    customCardback: String,
    customCardbackSaveTime: String,
    customCardbackUid: String,
    enableTimestamps: Boolean,
    enableRightSidebarInGame: Boolean,
    disablePlayerColorsInChat: Boolean,
    disablePlayerCardbacks: Boolean,
    disableHelpMessages: Boolean,
    disableHelpIcons: Boolean,
    disableConfetti: Boolean,
    disableCrowns: Boolean,
    disableSeasonal: Boolean,
    disableAggregations: Boolean,
    disableKillConfirmation: Boolean,
    soundStatus: String,
    unbanTime: Date,
    unTimeoutTime: Date,
    fontSize: Number,
    fontFamily: String,
    isPrivate: Boolean,
    privateToggleTime: Number,
    blacklist: Array,
    tournyWins: Array,
    hasChangedName: Boolean,
    previousSeasonAward: String,
    specialTournamentStatus: String,
    disableElo: Boolean,
    fullheight: Boolean,
    safeForWork: Boolean,
    keyboardShortcuts: String,
    notifyForNewLobby: Boolean,
    gameFilters: {
      pub: Boolean,
      priv: Boolean,
      unstarted: Boolean,
      inprogress: Boolean,
      completed: Boolean,
      customgame: Boolean,
      casualgame: Boolean,
      timedMode: Boolean,
      standard: Boolean,
      rainbow: Boolean,
    },
    gameNotes: {
      top: Number,
      left: Number,
      width: Number,
      height: Number,
    },
    playerNotes: Array,
    ignoreIPBans: Boolean,
    truncatedSize: Number,
    claimCharacters: String,
    claimButtons: String,
  },
  verification: {
    email: String,
  },
  signupIP: String,
  lastConnectedIP: String,
  lastConnected: Date,
  ipHistory: Array,
  verified: Boolean,
  isBanned: Boolean,
  isTimeout: Date,
  touLastAgreed: String,
  bio: String,
  games: Array,
  wins: Number,
  losses: Number,
  rainbowWins: Number,
  rainbowLosses: Number,
  ...seasonalCounters,
  previousDayElo: Number,
  previousDayXP: Number,
  created: Date,
  isOnFire: Boolean,
  lastCompletedGame: Date,
  // Only ranked S25 games qualify; older/general completion timestamps must not stand in for this.
  lastRankedGameAt: Date,
  lastVersionSeen: String,
  isFixed: Boolean,
  eloSeason: Number,
  eloOverall: Number,
  // Retain historical snapshots and the cutover marker for offline migration evidence.
  legacyEloOverallS23: Number,
  legacyEloSeasonS23: Number,
  ratingVersion: Number,
  // One lifetime hidden estimator; eloOverall/eloSeason are independent public accumulators.
  // Leave the pair unset so R1 can seed a missing estimate from legacy Elo instead of treating a
  // veteran as fresh. Old Mongo season/display fields may still hydrate, but are no longer written.
  rating: {
    overall: {
      mu: Number,
      sigma: Number,
    },
  },
  hashUid: String,
  discordUsername: String,
  discordDiscriminator: String,
  discordMFA: Boolean,
  discordUID: String,
  githubUsername: String,
  githubMFA: Boolean,
  warnings: Array, // {text: String, moderator: String, time: Date, acknowledged: Boolean},
  feedbackSubmissions: Array, // { time: Date, text: String }
  primaryColor: String,
  secondaryColor: String,
  tertiaryColor: String,
  backgroundColor: String,
  textColor: String,
  eloPercentile: {
    seasonal: Number,
    overall: Number,
  },
  isRainbowSeason: Boolean,
  isRainbowOverall: Boolean,
  xpOverall: { type: Number, default: 0 },
  xpSeason: { type: Number, default: 0 },
  dateRainbowOverall: Date,
  badges: [{ id: String, text: String, title: String, dateAwarded: Date }],
  maxElo: { type: Number, default: STARTING_PUBLIC_RATING },
  pastElo: [{ date: Date, value: Number }],
  isTournamentMod: Boolean,
});

Account.plugin(passportLocalMongoose);

module.exports = mongoose.model("Account", Account);
